# https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/keymap-default.toml
[[mgr.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "go git toplevel"

[[mgr.prepend_keymap]]
on = ["<Esc>"]
run = "quit"
desc = "quit"

[[input.prepend_keymap]]
on = "<Esc>"
run = "close"
desc = "Cancel input"

