#!/bin/sh

if type xremap >/dev/null 2>&1; then
  xremap ~/.xremap &
fi

if type xfce4-panel >/dev/null 2>&1; then
  xfce4-panel &
elif type waybar >/dev/null 2>&1; then
  waybar &
fi

# clipboard
if type wl-paste >/dev/null 2>&1 && type cliphist >/dev/null 2>&1; then
  wl-paste --watch cliphist store &
fi

# ime
if type fcitx5 >/dev/null 2>&1; then
  fcitx5 >~/fcitx5.log 2>&1 &
fi

# monitoring
# conky&
# notification daemon
# dunst&
# wallpaper
# swww init
