#!/bin/sh

if type xremap >/dev/null 2>&1; then
  xremap ~/.xremap &
fi

if type waybar >/dev/null 2>&1; then
  waybar &
elif type sfwbar >/dev/null 2>&1; then
  sfwbar &
elif type xfce4-panel >/dev/null 2>&1; then
  xfce4-panel &
fi

# clipboard
if type wl-paste >/dev/null 2>&1 && type cliphist >/dev/null 2>&1; then
  wl-paste --watch cliphist store &
fi

# ime
if type fcitx5 >/dev/null 2>&1; then
  fcitx5 >~/fcitx5.log 2>&1 &
fi

# wlr-randr
if type kanshi >/dev/null 2>&1; then
  kanshi&
fi

# notification daemon
if type dunst >/dev/null 2>&1; then
  dunst&
elif type mako >/dev/null 2>&1; then
  mako&
fi

# conky&
# if type conky >/dev/null 2>&1; then
#   conky&
# fi

# wallpaper
# swww init
