#!/bin/sh
xremap ~/.xremap &

if type waybar >/dev/null 2>&1; then
  waybar &
fi

# ime
if type fcitx5 >/dev/null 2>&1; then
  fcitx5 &
fi

# monitoring
# conky&
# notification daemon
# dunst&
# wallpaper
# swww init
# clipboard
