font=monospace:size=13
initial-window-size-chars=80x40

[main]
# include=/usr/share/foot/themes/selenized-light
# include=/usr/share/foot/themes/gruvbox-light
include=/usr/share/foot/themes/solarized-light
# include=/usr/share/foot/themes/tempus-autumn
# include=/usr/share/foot/themes/tokyonight-light
# include=/usr/share/foot/themes/paper-color
# include=/usr/share/foot/themes/catppuccin-latte
# include=/usr/share/foot/themes/gruvbox-light
